Add drawer
suda-3156/htmlcss pull request #3
Opened 2024-07-04 08:38 UTC by suda-3156

ヘッダーとドロワーを作成し、ページ遷移をできるようにしました。
レビューお願いします。

2024-07-05 04:19 UTC, kss-iharuya requested changes
仕様通りの動作になっていることを確認しました。

いくつかベターな書き方を提案したので修正してからマージしてください。（もし必要であればまたレビューを割り当ててください。）

2024-07-05 04:19 UTC, kss-iharuya commented on app.js
> +const header = document.querySelector("#header");
スクロールしたらヘッダーがちょっと小さくなるUIいいね！

2024-07-05 04:19 UTC, kss-iharuya commented on app.js
> +const header = document.querySelector("#header");
読み間違いじゃなかったら、`window.addEventListener("scroll")`のコールバック関数は直接書くのじゃなくて、`function updateHeaderStyle() {...}`みたいな感じに別の関数に書くと可読性高くなるかも。

2024-07-05 04:19 UTC, kss-iharuya commented on app.js
> +hamburger.onkeydown = (event) => {
この処理は<button>には必要？

2024-07-05 04:19 UTC, kss-iharuya commented on index.html
> +            <div class="hamburger" tabindex="0" role="button">
`<button>`を使ってください。純粋なHTML要素が使えるときはそっちを使うようにすることでa11y方面での安定性が高まります。

2024-07-05 04:21 UTC, kss-iharuya commented
This pr is implementation of #2

2024-07-05 09:07 UTC, suda-3156 commented
@kss-iharuya 
これで合っているかの確認と、コメントの仕方を確認したかったのでお願いします。

ハンバーガーボタンを<button>を使用するように変更しました。(~.htmlとstyle.css,app.jsを変更)
また、headerを小さくする関数に関して、実行される関数を別で書きました。(app.jsを変更)

2024-07-09 07:48 UTC, kss-iharuya approved these changes
LGTM

2024-07-09 13:10 UTC, merged